site_name : PayEx Checkout
theme : yeti
repo_url : https://github.com/PayEx/PayEx.Checkout.Documentation
site_favicon : favicon.png
# TODO site_url: https://checkout.payex.com
# TODO site_description: modern payment solution
site_author : PayEx Team User Experience #TODO change
copyright : Copyright © PayEx. All Rights Reserved.

pages :
- Home : index.md
- Get in touch : getInTouch.md
- Getting started :
  - Implementation: implementation.md
  - Credentials : credentials.md
  - Go live procedure : goLiveProcedure.md
- Frontend API :
  - Configuration reference : configurationReference.md
- Backend API:
  - Overview : backend.md
  - Payment : payment.md
  - Address : address.md
  - Transaction : transaction.md
  - Callbacks: callbacks.md

