site_name : Payex Checkout
theme : readthedocs
repo_url : https://github.com/PayEx/PayEx.Checkout.Documentation
site_favicon : favicon.png
# TODO site_url: https://checkout.payex.com
# TODO site_description: modern payment solution
site_author : Payex Team User Experience #TODO change
copyright : Copyright © PayEx. All Rights Reserved.
pages :
- 1. Home : index.md
- 2. Authentication : authentication.md
- 3. Frontend :
  - 3.1 Getting started : gettingStarted.md
  - 3.2 Configuration reference : configurationReference.md
- 4. Backend :
  - 4.1 Payment: payment.md
  - 4.2 Address : address.md
  - 4.3 Transaction : transaction.md
