site_name : Payex Checkout
theme : readthedocs
pages :
- Home : index.md
- Authentication : authentication.md
- Frontend :
  - Getting started : gettingStarted.md
  - Configuration reference : configurationReference.md
- API reference :
  - Payment: payment.md
  - Address : address.md
  - Transaction : transaction.md
