site_name : Payex Checkout
theme : readthedocs
pages :
- Home : index.md
- Authentication : authentication.md
- Server resources :
   - Address.md
   - Capture.md
   - Cancel.md
- Frontend :
   - Getting started : gettingStarted.md
   - Configuration reference : configurationReference.md
