site_name : PayEx Checkout
theme : readthedocs
repo_url : https://github.com/PayEx/PayEx.Checkout.Documentation
# TODO site_url: https://checkout.payex.com
# TODO site_description: modern payment solution
site_author : PayEx Team User Experience #TODO change
copyright : Copyright © PayEx. All Rights Reserved.
site_favicon : img/favicon.png

pages :
- Home : index.md
